services:
  qgis-server:
    image: qgis/qgis-server:3.34-noble
    volumes:
      - ./qgis/data:/data:ro
    environment:
      - LANG=en_EN.UTF-8
      - QGIS_PROJECT_FILE=/data/osm.qgs
      - QGIS_SERVER_LOG_LEVEL=0
      - DEBUG=1

  nginx:
    image: nginx:1.26
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-server
